CREATE DATABASE SalesCaseStudy;

USE SalesCaseStudy;

-------------------------Tasks to be performed:-----------------------------
--------------1. Display the number of states present in the LocationTable.
------Answer 1
SELECT COUNT(DISTINCT State) AS NumberOfStates
FROM Location;



----------------2. How many products are of regular type?
-------Answer 2
SELECT COUNT(*) AS RegularProducts
FROM Product
WHERE Type = 'Regular';



----------------3. How much spending has been done on marketing of product ID 1?
---------Answer 3
SELECT SUM(Marketing) AS TotalMarketingSpend
FROM Fact
WHERE ProductID = 1;



----------------------------4. What is the minimum sales of a product?
-------Answer 4
SELECT MIN(Sales) AS MinimumSales
FROM Fact;



---------------------------5. Display the max Cost of Good Sold (COGS).
-------Answer 5
SELECT MAX(COGS) AS MaxCOGS
FROM Fact;



--------------------6. Display the details of the product where product type is coffee
--------Answer 6
SELECT *
FROM Product
WHERE [Product_Type] = 'Coffee';



------------------7. Display the details where total expenses are greater than 40.
---------Answer 7
SELECT *
FROM Fact
WHERE [Total_Expenses] > 40;



----------------8. What is the average sales in area code 719?
--------Answer 8
SELECT AVG(Sales) AS AverageSales
FROM Fact
WHERE [Area_Code] = 719;



----------------9. Find out the total profit generated by Colorado state.
--------Answer 9
SELECT SUM(F.Profit) AS TotalProfit
FROM Fact AS F
INNER JOIN Location AS L
    ON F.[Area_Code] = L.Area_Code
WHERE L.State = 'Colorado';



--------------10. Display the average inventory for each product ID
-------Answer 10
SELECT 
    ProductID,
    AVG(Inventory) AS AverageInventory
FROM Fact
GROUP BY ProductID;



--------------11. Display state in a sequential order in a Location Table.
------Answer 11
SELECT *
FROM Location
ORDER BY State ASC;



-------------12. Display the average budget of the Product where the average budget margin should be 
-------------greater than 100.
-----Answer 12
SELECT
    ProductID,
    AVG([Budget_Profit]) AS AverageBudget
FROM Fact
GROUP BY ProductID
HAVING AVG([Budget_Margin]) > 100;



-----------------13. What is the total sales done on date 2010-01-01?
-------Answer 13
SELECT SUM(Sales) AS TotalSales
FROM Fact
WHERE [Date] = '2010-01-01';



--------------14. Display the average total expense of each product ID on an individual date.
--------Answer 14
SELECT
    [Date],
    ProductID,
    AVG([Total_Expenses]) AS AverageTotalExpense
FROM Fact
GROUP BY [Date], ProductID
ORDER BY [Date], ProductID;



-------------------15. Display the table with the following attributes such as date, 
-------------------productID, product_type, product, sales, profit, state, area_code.
---------Answer 15
SELECT
    F.[Date],
    F.ProductID,
    P.[Product_Type],
    P.Product,
    F.Sales,
    F.Profit,
    L.State,
    F.[Area_Code]
FROM Fact AS F
INNER JOIN Product AS P
    ON F.ProductID = P.ProductID
INNER JOIN Location AS L
    ON F.[Area_Code] = L.Area_Code;



------------------16. Display the rank without any gap to show the sales wise rank.
-------Answer 16
SELECT
    ProductID,
    Sales,
    DENSE_RANK() OVER (ORDER BY Sales DESC) AS SalesRank
FROM Fact
ORDER BY Sales DESC;



-------------------17. Find the state wise profit and sales.
-------Answer 17
SELECT
    L.State,
    SUM(F.Profit) AS TotalProfit,
    SUM(F.Sales) AS TotalSales
FROM Fact AS F
INNER JOIN Location AS L
    ON F.[Area_Code] = L.Area_Code
GROUP BY L.State
ORDER BY L.State;



----------------------18. Find the state wise profit and sales along with the productname.
----------Answer 18
SELECT
    L.State,
    P.Product,
    SUM(F.Profit) AS TotalProfit,
    SUM(F.Sales) AS TotalSales
FROM Fact AS F
INNER JOIN Location AS L
    ON F.[Area_Code] = L.Area_Code
INNER JOIN Product AS P
    ON F.ProductID = P.ProductID
GROUP BY
    L.State,
    P.Product
ORDER BY
    L.State,
    P.Product;



--------------------19. If there is an increase in sales of 5%, calculate the increasedsales.
---------Answer 19
SELECT
    ProductID,
    Sales,
    Sales * 1.05 AS IncreasedSales
FROM Fact;



--------------------20. Find the maximum profit along with the product ID and producttype.
----------Answer 20
SELECT TOP 1
    F.ProductID,
    P.[Product_Type],
    F.Profit
FROM Fact AS F
INNER JOIN Product AS P
    ON F.ProductID = P.ProductID
ORDER BY F.Profit DESC;



-----------------21. Create a stored procedure to fetch the result according to the product 
-----------------typefrom Product Table.
-----Answer 21
CREATE PROCEDURE GetProductsByType
    @ProductType VARCHAR(50)
AS
BEGIN
    SELECT *
    FROM Product
    WHERE [Product_Type] = @ProductType;
END;

EXEC GetProductsByType @ProductType = 'Coffee';



-------------------22. Write a query by creating a condition in which if the total expenses is 
-------------------lessthan60 then it is a profit or else loss.
--------Answer 22
SELECT
    [Total_Expenses],
    CASE
        WHEN [Total_Expenses] < 60 THEN 'Profit'
        ELSE 'Loss'
    END AS Status
FROM Fact;



-------------------23. Give the total weekly sales value with the date and product IDdetails. 
-------------------Useroll-up to pull the data in hierarchical order.
------Answer 23
SELECT
    DATEPART(YEAR, [Date]) AS SalesYear,
    DATEPART(WEEK, [Date]) AS SalesWeek,
    [Date],
    ProductID,
    SUM(Sales) AS TotalSales
FROM Fact
GROUP BY ROLLUP
(
    DATEPART(YEAR, [Date]),
    DATEPART(WEEK, [Date]),
    [Date],
    ProductID
)
ORDER BY
    SalesYear,
    SalesWeek,
    [Date],
    ProductID;



-----------------24. Apply union and intersection operator on the tables which consist of
-----------------attribute area code.
-----------Answer 24
----UNION
SELECT [Area_Code] AS AreaCode
FROM Fact

UNION

SELECT Area_Code
FROM Location;

----INTERSECT
SELECT [Area_Code] AS AreaCode
FROM Fact

INTERSECT

SELECT Area_Code
FROM Location;



------------------25. Create a user-defined function for the product table to fetch a particular
------------------product type based upon the user’s preference.
----------Answer 25
CREATE FUNCTION GetProductByType
(
    @ProductType VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT *
    FROM Product
    WHERE [Product_Type] = @ProductType
);

SELECT *
FROM GetProductByType('Coffee');



-------------------26. Change the product type from coffee to tea where product IDis 1 andundoit.
---------Answer 26
BEGIN TRANSACTION;

UPDATE Product
SET [Product_Type] = 'Tea'
WHERE ProductID = 1;

SELECT *
FROM Product
WHERE ProductID = 1;

ROLLBACK TRANSACTION;

SELECT *
FROM Product
WHERE ProductID = 1;



-----------------------27. Display the date, product ID and sales where total expenses are
-----------------------between 100 to 200.
----------Answer 27
SELECT
    [Date],
    ProductID,
    Sales
FROM Fact
WHERE [Total_Expenses] BETWEEN 100 AND 200;



--------------------28. Delete the records in the Product Table for regular type.
------------Answer 28
DELETE FROM Product
WHERE Type = 'Regular';



-------------------29. Display the ASCII value of the fifth character from the columnProduct.
-----------Answer 29
SELECT
    Product,
    ASCII(SUBSTRING(Product, 5, 1)) AS ASCII_Value
FROM Product;


